### ISSUE TITLE
Data split for physionet

### ISSUE THREAD

**Issue by sindhura97** [imJiawen/Warpformer#1]
Hi, for the physionet 2012 challenge, from the code (get_physionet_data() in Dataset_MM.py), it seems like only "set a" was used to generate all three train, validation, and test splits. Sets "b" and "c" were not used. Could you confirm if this is true and if this is the same setup used for the results reported in the paper?

**Comment by imJiawen** [comment]
Yes, this is true. It is important to note that in the PhysioNet dataset, only 4000 instances (the data in set-a) are labeled, and the remaining labels are unavailable. Thus, in the context of the supervised classification task, we exclusively utilize the data from set-a as the training, validation, and test sets. We reuse the data acquisition scripts for PhysioNet and Human Activity from [mTAN](https://github.com/reml-lab/mTAN).
