### ISSUE TITLE
Bugs in MIMIC data processing code ??

### ISSUE THREAD

**Issue by sindhura97** [imJiawen/Warpformer#2]
1. In line 331 of preprocess_mimic_iii_large.py, events table is initialized and this makes it lose all the variables extracted before Ultifiltrate. Is this a bug? Should ev_k be appended to events in line 331 instead of "events = ev_k.copy()" ?

2. I am getting the following error (shown below) while running split_data_preprocessing_large.py. 
Traceback (most recent call last):
  File "split_data_preprocessing_large.py", line 290, in <module>
    mor_adm_icu_id, mor_data, mor_label = create_mor_large(adm, events, adm2subj_dict, feature_map, filt_adm_ids=train_adm_id,)
  File "./proc_util/task_build.py", line 30, in create_mor_large
    patient[feature_map[row.NAME]].append((row.CHARTTIME, row.VALUENUM))
KeyError: 'Pre-admission Intake'
I think this is because of removing some features in lines 263-276 of split_data_preprocessing_large.py.
Can you edit line 30 of task_build.py to run only if row.NAME is in feature_map?

**Comment by sindhura97** [comment]
I am doing some checks on my end to make sure preprocess_mimic_iii_large.py ran as expected. I will reopen this issue if it still persists later.

**Comment by imJiawen** [comment]
Hi @sindhura97 . Thank you for your valuable feedback. I have addressed all the issues you mentioned and made the necessary fixes. Please pull the latest version from the repository. If you come across any further bugs or have any additional feedback, please don't hesitate to let me know.
